package demo.urlshortener;
import demo.urlshortener.orchestration.*;import java.util.*;import java.util.concurrent.atomic.AtomicInteger;import java.nio.file.*;import java.time.*;
public final class TestRunner {
 public static void main(String[] args) throws Exception {serviceTest();durabilityAndControlsTest();workflowTest();plannerAndIdempotencyTest();System.out.println("ALL TESTS PASSED");}
 static void serviceTest(){UrlService s=new UrlService(new InMemoryUrlRepository(),new ShortCodeGenerator());UrlLink a=s.shorten("https://example.com/path");check(a.code().length()>0,"code");check(s.resolve(a.code()).visits()==1,"visit");check(s.analytics(a.code()).visits()==1,"analytics");try{s.shorten("file:///etc/passwd");throw new AssertionError("invalid accepted");}catch(IllegalArgumentException expected){}}
 static void workflowTest(){AtomicInteger n=new AtomicInteger();var retry=new WorkflowEngine.Node("build",Set.of(),false,2,()->{if(n.incrementAndGet()==1)throw new RuntimeException("transient");return "ok";},null);var gate=new WorkflowEngine.Node("release",Set.of("build"),true,1,()->"released",null);var waiting=new WorkflowEngine(List.of(retry,gate),Set.of()).execute();check(waiting.states().get("release")==WorkflowEngine.Status.WAITING_APPROVAL,"approval");var ok=new WorkflowEngine(List.of(retry,gate),Set.of("release")).execute();check(ok.states().get("release")==WorkflowEngine.Status.SUCCEEDED,"release");check(ok.retries()==0||ok.retries()==1,"retry metric");}
 static void durabilityAndControlsTest() throws Exception {Path dir=Files.createTempDirectory("url-shortener-test");Path store=dir.resolve("links.bin");UrlService first=new UrlService(new LocalPlatform.DurableUrlRepository(store),new ShortCodeGenerator());UrlLink x=first.shorten("https://example.org");first.resolve(x.code());UrlService reloaded=new UrlService(new LocalPlatform.DurableUrlRepository(store),new ShortCodeGenerator());check(reloaded.analytics(x.code()).visits()==1,"durable analytics");var limiter=new LocalPlatform.FixedWindowRateLimiter(1,Duration.ofMinutes(1));check(limiter.allow("a")&&!limiter.allow("a"),"rate limit");var denied=new WorkflowEngine(List.of(new WorkflowEngine.Node("deploy",Set.of(),false,1,()->"bad",null)),Set.of(),n->Optional.of("change ticket absent"),null).execute();check(denied.states().get("deploy")==WorkflowEngine.Status.FAILED,"policy denial");}
 static void plannerAndIdempotencyTest() throws Exception {var a=new WorkflowEngine.Node("a",Set.of(),false,1,()->"",null);var b=new WorkflowEngine.Node("b",Set.of("a"),false,1,()->"",null);var c=new WorkflowEngine.Node("c",Set.of("b"),false,1,()->"",null);check(WorkflowPlanner.transitiveDependents(List.of(a,b,c),"a").equals(new LinkedHashSet<>(List.of("a","b","c"))),"replan impact");Path dir=Files.createTempDirectory("idem-test");var keys=new LocalPlatform.IdempotencyStore(dir.resolve("keys.bin"));AtomicInteger calls=new AtomicInteger();UrlLink one=keys.create("request-1","same",()->new UrlLink("x","https://example.com","alice",Instant.now(),calls.incrementAndGet()));UrlLink two=keys.create("request-1","same",()->new UrlLink("y","https://example.com","alice",Instant.now(),calls.incrementAndGet()));check(one.code().equals(two.code())&&calls.get()==1,"idempotency");var auth=new LocalPlatform.Auth();check(auth.authenticate("local-user-key").has(LocalPlatform.Role.USER),"authenticate");try{auth.require(auth.authenticate("local-user-key"),LocalPlatform.Role.RELEASE_MANAGER);throw new AssertionError("authorization bypass");}catch(LocalPlatform.AccessDenied expected){}}
 static void check(boolean condition,String label){if(!condition)throw new AssertionError(label);}
}
